const mealTypes=[['breakfast','Breakfast'],['lunch','Lunch'],['dinner','Dinner'],['snack','Snack']];
const esc=escapeHTML;
function mealMonthEntries(){const prefix=mk()+'-';const out=[];Object.entries(db.meals||{}).forEach(([date,day])=>{if(!date.startsWith(prefix)||!day||typeof day!=='object')return;mealTypes.forEach(([key,label])=>{if(day?.[key])out.push({date,key,label,...day[key]})})});return out;}
function selectedMealDate(){const current=new Date((state.mealDate||iso(today))+'T12:00:00');if(current.getFullYear()===state.year&&current.getMonth()===state.month)return iso(current);const day=Math.min(today.getDate(),daysIn(state.year,state.month));return `${state.year}-${pad(state.month+1)}-${pad(day)}`;}
function setMealsView(v){if(v==='daily'&&state.mealsView!=='daily')state.mealDate=selectedMealDate();state.mealsView=v;renderMeals();}
function mealSourceLabel(source){return source==='prep'?'Meal prep':source==='leftover'?'Leftovers':'Takeaway'}
function mealSourceClass(source){return source==='prep'?'prep':source==='leftover'?'leftover':'take'}
function renderMeals(){
 state.route='meals';$$('.nav-btn[data-route]').forEach(b=>b.classList.toggle('active',b.dataset.route==='home'));
 if(state.mealsView==='daily')return renderMealsDaily();
 const entries=mealMonthEntries(),mainMeals=entries.filter(x=>x.key!=='snack'),snacks=entries.filter(x=>x.key==='snack');
 const prep=mainMeals.filter(x=>x.source==='prep').length,take=mainMeals.filter(x=>x.source==='takeaway').length,cost=entries.reduce((s,x)=>s+Number(x.cost||0),0);
 main.innerHTML=`<div class="meals-page"><div class="section-head"><div><h1 class="page-title">Meals</h1><div class="subtle">Monthly meals · snacks · spending</div></div><button class="btn" onclick="openMealEditor()">Add meal</button></div><div class="tabs meals-tabs"><button class="active" onclick="setMealsView('monthly')">Monthly</button><button onclick="setMealsView('daily')">Daily</button></div>${monthNav()}<section class="meal-summary-grid meal-summary-grid-four"><div class="card meal-summary"><span>⌂</span><strong>Meal prep</strong><b>${prep} meals</b><em>this month</em></div><div class="card meal-summary"><span>▣</span><strong>Takeaways</strong><b>${take} meals</b><em>this month</em></div><div class="card meal-summary"><span>$</span><strong>Food spending</strong><b>${fmtMoney(cost)}</b><em>this month</em></div><div class="card meal-summary"><span>✦</span><strong>Snacks</strong><b>${snacks.length}</b><em>this month</em></div></section><section class="card meal-radial-card" id="mealRadial"></section><section class="section"><button class="btn meal-daily-cta" onclick="setMealsView('daily')">View daily records</button></section></div>`;
 drawMealRadial();
}
function drawMealRadial(){
 const el=$('#mealRadial');if(!el)return;
 const n=daysIn(state.year,state.month),step=360/n;
 const colours={dinner:{prep:'#C5E1A5',leftover:'#E5F1D5'},lunch:{prep:'#B3E5FC',leftover:'#DDF3FD'},breakfast:{prep:'#F9E7A3',leftover:'#FFF4CB'}};
 const rings={breakfast:[78,104],lunch:[108,134],dinner:[138,164]};
 const sourceFill=(meal,key)=>!meal||meal.source==='takeaway'?'#ffffff':(colours[key][meal.source]||'#ffffff');
 let svg=`<svg viewBox="0 0 400 400" aria-label="Monthly meals radial calendar"><circle cx="200" cy="200" r="68" fill="#f8fbfc"/>`;
 for(let d=1;d<=n;d++){
  const date=`${mk()}-${pad(d)}`,day=db.meals[date]||{},a0=(d-1)*step+.7,a1=d*step-.7,mid=(a0+a1)/2;
  ['breakfast','lunch','dinner'].forEach(key=>{const [r0,r1]=rings[key];svg+=`<path d="${wedge(200,200,r0,r1,a0,a1)}" fill="${sourceFill(day[key],key)}" stroke="#e5ebef" stroke-width="1" onclick="openMealEditor('${key}','${date}')"/>`});
  if(day.snack){const anchor=day.snack.withMeal&&rings[day.snack.withMeal]?day.snack.withMeal:'lunch',[r0,r1]=rings[anchor],p=polar(200,200,(r0+r1)/2,mid);svg+=`<text x="${p.x}" y="${p.y+4}" text-anchor="middle" class="meal-snack-sparkle" pointer-events="none">✦</text>`;}
  const p=polar(200,200,180,mid),weekday=['Su','Mo','Tu','We','Th','Fr','Sa'][new Date(state.year,state.month,d,12).getDay()];
  svg+=`<text x="${p.x}" y="${p.y-2}" text-anchor="middle" class="meal-radial-day"><tspan x="${p.x}" class="meal-radial-date">${d}</tspan><tspan x="${p.x}" dy="8" class="meal-radial-weekday">${weekday}</tspan></text>`;
 }
 svg+=`<text x="200" y="197" text-anchor="middle" class="meal-radial-center">${monthName(state.year,state.month)}</text><text x="200" y="216" text-anchor="middle" class="meal-radial-sub">meals</text></svg>`;
 el.innerHTML=svg;
}
function renderMealsDaily(){const date=state.mealDate||iso(today),day=db.meals[date]||{};main.innerHTML=`<div class="meals-page"><div class="section-head"><div><h1 class="page-title">Meals</h1><div class="subtle">Daily record</div></div><button class="btn" onclick="openMealEditor()">Add meal</button></div><div class="tabs meals-tabs"><button onclick="setMealsView('monthly')">Monthly</button><button class="active" onclick="setMealsView('daily')">Daily</button></div><div class="meal-date-nav"><button onclick="shiftMealDay(-1)">‹</button><strong>${new Date(date+'T12:00:00').toLocaleDateString('en-AU',{weekday:'short',day:'numeric',month:'short',year:'numeric'})}</strong><button onclick="shiftMealDay(1)">›</button></div><section class="meal-day-list">${mealTypes.map(([key,label])=>{const x=day[key];return `<button class="card meal-row" onclick="openMealEditor('${key}')"><span class="meal-type-icon">${key==='breakfast'?'☀':key==='lunch'?'◐':key==='dinner'?'☾':'✦'}</span><span class="meal-row-copy"><strong>${label}</strong>${x?`<small>${esc(x.food||'No food note')}</small><em class="${mealSourceClass(x.source)}">${mealSourceLabel(x.source)}</em>${key==='snack'&&x.withMeal?`<small>With ${esc(x.withMeal)}</small>`:''}${x.place?`<small>${esc(x.place)}</small>`:''}${x.notes?`<small class="meal-note">${esc(x.notes)}</small>`:''}`:'<small>Not recorded</small>'}</span><b>${x?.cost?fmtMoney(x.cost):''}</b><span>›</span></button>`}).join('')}</section></div>`;}
function shiftMealDay(delta){const d=new Date((state.mealDate||iso(today))+'T12:00:00');d.setDate(d.getDate()+delta);state.mealDate=iso(d);state.year=d.getFullYear();state.month=d.getMonth();renderMealsDaily();}
function openMealEditor(type='breakfast',dateOverride=''){const date=dateOverride||((state.mealsView==='monthly')?selectedMealDate():(state.mealDate||iso(today))),x=db.meals[date]?.[type]||{};const root=$('#modalRoot');root.innerHTML=`<div class="modal-backdrop" onclick="if(event.target===this)closeMealEditor()"><div class="modal"><h2>${x.source?'Edit':'Add'} meal</h2><div class="field"><label>Date</label><input id="mealDate" type="date" value="${date}"></div><div class="field"><label>Which meal?</label><select id="mealType" onchange="toggleSnackMealField(this.value)">${mealTypes.map(([k,l])=>`<option value="${k}" ${k===type?'selected':''}>${l}</option>`).join('')}</select></div><div class="field"><label>Meal type</label><select id="mealSource"><option value="prep" ${x.source==='prep'?'selected':''}>Home-prepared</option><option value="leftover" ${x.source==='leftover'?'selected':''}>Leftovers</option><option value="takeaway" ${x.source==='takeaway'?'selected':''}>Takeaway</option></select></div><div class="field snack-with-field" id="snackWithField" ${type==='snack'?'':'hidden'}><label>Snack with</label><select id="snackWithMeal"><option value="breakfast" ${x.withMeal==='breakfast'?'selected':''}>Breakfast</option><option value="lunch" ${!x.withMeal||x.withMeal==='lunch'?'selected':''}>Lunch</option><option value="dinner" ${x.withMeal==='dinner'?'selected':''}>Dinner</option></select></div><div class="field"><label>Food / meal</label><input id="mealFood" value="${esc(x.food||'')}" placeholder="e.g. chicken salad"></div><div class="field"><label>Food chain / grocery</label><input id="mealPlace" value="${esc(x.place||'')}" placeholder="e.g. Woolworths, Sushi Hub"></div><div class="field"><label>Cost</label><input id="mealCost" type="number" min="0" step="0.01" inputmode="decimal" value="${x.cost??''}" placeholder="0.00"></div><div class="field"><label>Notes (optional)</label><textarea id="mealNotes" placeholder="Add a note">${esc(x.notes||'')}</textarea></div><div class="btn-row"><button class="btn secondary" onclick="closeMealEditor()">Cancel</button><button class="btn" onclick="saveMealEntry('${date}','${type}')">Save meal</button></div></div></div>`;}
function toggleSnackMealField(type){const f=$('#snackWithField');if(f)f.hidden=type!=='snack'}
function closeMealEditor(){$('#modalRoot').innerHTML='';}
function saveMealEntry(originalDate,originalType){const date=$('#mealDate').value,type=$('#mealType').value;if(!date)return;if((date!==originalDate||type!==originalType)&&db.meals[originalDate]?.[originalType]){delete db.meals[originalDate][originalType];if(!Object.keys(db.meals[originalDate]).length)delete db.meals[originalDate];}db.meals[date]=db.meals[date]||{};db.meals[date][type]={source:$('#mealSource').value,food:$('#mealFood').value.trim(),place:$('#mealPlace').value.trim(),cost:Math.max(0,Number($('#mealCost').value||0)),notes:$('#mealNotes').value.trim(),...(type==='snack'?{withMeal:$('#snackWithMeal')?.value||'lunch'}:{})};save();state.mealDate=date;const d=new Date(date+'T12:00:00');state.year=d.getFullYear();state.month=d.getMonth();state.mealsView='monthly';closeMealEditor();renderMeals();}
