function modal(html){$('#modalRoot').innerHTML=`<div class="modal-backdrop" onclick="if(event.target===this)closeModal()"><div class="modal">${html}</div></div>`}function closeModal(){$('#modalRoot').innerHTML=''}
function openQuickAdd(){modal(`<h2>What do you want to log?</h2><div class="choice-grid"><button class="choice" onclick="openPurchase()">🛍️<br>Purchase</button><button class="choice" onclick="openSleepMood('${iso(today)}')">🌙<br>Sleep + Mood</button><button class="choice" onclick="openPeriod('${iso(today)}')">🩸<br>Period</button><button class="choice" onclick="openWaterSugar('${iso(today)}')">💧<br>Water + Sugar</button></div><div class="btn-row"><button class="btn secondary" onclick="closeModal()">Cancel</button></div>`)}
function openPurchase(){modal(`<h2>Add purchase</h2><div class="form-grid"><div class="field"><label>Date</label><input id="pDate" type="date" value="${iso(today)}"></div><div class="field"><label>Type</label><select id="pType"><option value="inStore">In store</option><option value="online">Online</option></select></div><div class="field"><label>Store</label><input id="pStore" placeholder="e.g. Kmart"></div><div class="field"><label>Item</label><input id="pItem" placeholder="What did you buy?"></div><div class="field"><label>Amount</label><input id="pAmount" type="number" step="0.01" inputmode="decimal"></div><div class="field"><label>Card</label><select id="pCard"><option>Mx</option><option>Up</option><option>Co</option></select></div><div class="field"><label>Expected arrival (online)</label><input id="pDelivery" type="date"></div><div class="field"><label>Tax review</label><select id="pTax"><option value="no">Not marked</option><option value="potential">Potential nurse-related deduction</option></select></div></div><div class="notice" style="margin-top:10px">Potential tax-deductible means “flag for review”, not confirmed deductible.</div><div class="btn-row"><button class="btn secondary" onclick="closeModal()">Cancel</button><button class="btn" onclick="savePurchase()">Save</button></div>`)}
function savePurchase(){const p={id:uid(),date:$('#pDate').value,store:$('#pStore').value.trim()||'Unknown store',item:$('#pItem').value.trim()||'Purchase',amount:Number($('#pAmount').value||0),type:$('#pType').value,card:$('#pCard').value,delivery:$('#pDelivery').value,tax:$('#pTax').value};db.purchases.push(p);save();closeModal();setRoute('spending')}
function openSleepMood(date){const v=db.sleepMood[date]||{};modal(`<h2>Sleep + Mood · ${fmtDate(date)}</h2><div class="field"><label>Sleep</label><div class="choice-grid" id="sleepChoices">${['2–3','4–5','6–7','>8'].map(x=>`<button class="choice ${v.sleep===x?'active':''}" data-v="${x}" onclick="chooseOne(this,'#sleepChoices')">${x} hours</button>`).join('')}</div></div><div class="field" style="margin-top:12px"><label>Mood</label><div class="choice-grid" id="moodChoices">${moodList.map(m=>`<button class="choice ${v.mood===m[1]?'active':''}" data-v="${m[1]}" onclick="chooseOne(this,'#moodChoices')">${moodArt(m[1],'choice-mood-art')}${m[0]}</button>`).join('')}</div></div><div class="btn-row"><button class="btn secondary" onclick="closeModal()">Cancel</button><button class="btn" onclick="saveSleepMood('${date}')">Save</button></div>`)}
function chooseOne(el,root){$$(root+' .choice').forEach(x=>x.classList.remove('active'));el.classList.add('active')}
function saveSleepMood(date){db.sleepMood[date]={sleep:$('#sleepChoices .active')?.dataset.v||'',mood:$('#moodChoices .active')?.dataset.v||''};save();closeModal();renderSleepMood()}
function openPeriod(date){const v=db.period[date]||{symptoms:[]};modal(`<h2>Period · ${fmtDate(date)}</h2><div class="field"><label>Bleeding intensity</label><div class="choice-grid" id="bleedChoices">${['None','Light','Moderate','Heavy'].map(x=>`<button class="choice ${v.bleeding===x?'active':''}" data-v="${x}" onclick="chooseOne(this,'#bleedChoices')">${x}</button>`).join('')}</div></div><div class="field" style="margin-top:12px"><label>Symptoms</label><div class="check-grid" id="symChoices">${symptoms.map(s=>`<button class="check-choice ${(v.symptoms||[]).includes(s[1])?'active':''}" data-v="${s[1]}" onclick="this.classList.toggle('active')"><img src="${symptomImg(s[1])}">${s[0]}</button>`).join('')}</div></div><div class="field" style="margin-top:12px"><label>Notes (optional)</label><textarea id="perNotes">${v.notes||''}</textarea></div><div class="btn-row"><button class="btn secondary" onclick="closeModal()">Cancel</button><button class="btn" onclick="savePeriod('${date}')">Save</button></div>`)}
function savePeriod(date){const bleeding=$('#bleedChoices .active')?.dataset.v||'None';db.period[date]={bleeding:bleeding==='None'?'':bleeding,symptoms:$$('#symChoices .active').map(x=>x.dataset.v),notes:$('#perNotes').value};save();closeModal();renderPeriod()}
function openWaterSugar(date){const v=db.waterSugar[date]||{};modal(`<h2>Water + Sugar · ${fmtDate(date)}</h2><div class="field"><label>Water intake</label><div class="choice-grid" id="waterChoices">${[1,2,3].map(x=>`<button class="choice ${Number(v.water)===x?'active':''}" data-v="${x}" onclick="chooseOne(this,'#waterChoices')">${x} L</button>`).join('')}</div></div><div class="field" style="margin-top:12px"><label>Sugar intake</label><div class="choice-grid" id="sugarChoices">${[0,1,2,3].map(x=>`<button class="choice ${Number(v.sugar)===x&&v.sugar!=null?'active':''}" data-v="${x}" onclick="chooseOne(this,'#sugarChoices')">${x===0?'None':x+' serving'+(x>1?'s':'')}</button>`).join('')}</div></div><div class="btn-row"><button class="btn secondary" onclick="closeModal()">Cancel</button><button class="btn" onclick="saveWaterSugar('${date}')">Save</button></div>`)}
function saveWaterSugar(date){db.waterSugar[date]={water:Number($('#waterChoices .active')?.dataset.v||0)||null,sugar:$('#sugarChoices .active')?Number($('#sugarChoices .active').dataset.v):null};save();closeModal();renderWaterSugar()}
function openLimits(){modal(`<h2>Card spending limits</h2><div class="form-grid">${['Mx','Up','Co'].map(c=>`<div class="field"><label>${c}</label><input id="lim${c}" type="number" step="1" value="${db.cardLimits[c]}"></div>`).join('')}</div><div class="btn-row"><button class="btn secondary" onclick="closeModal()">Cancel</button><button class="btn" onclick="['Mx','Up','Co'].forEach(c=>db.cardLimits[c]=Number($('#lim'+c).value||0));save();closeModal();renderMore()">Save</button></div>`)}
function openBudgets(){modal(`<h2>Monthly shopping budgets</h2><div class="form-grid"><div class="field"><label>In store</label><input id="bin" type="number" value="${db.budgets.inStore}"></div><div class="field"><label>Online</label><input id="bon" type="number" value="${db.budgets.online}"></div></div><div class="btn-row"><button class="btn secondary" onclick="closeModal()">Cancel</button><button class="btn" onclick="db.budgets={inStore:Number($('#bin').value||0),online:Number($('#bon').value||0)};save();closeModal();renderMore()">Save</button></div>`)}
function exportData(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({app:'Jest Life Tracker',version:1,data:db},null,2)],{type:'application/json'}));a.download=`jest-backup-${iso(today)}.json`;a.click();URL.revokeObjectURL(a.href)}
function importData(){const i=document.createElement('input');i.type='file';i.accept='.json,application/json';i.onchange=async()=>{try{const x=JSON.parse(await i.files[0].text());if(x.app!=='Jest Life Tracker'||x.version!==1||!x.data)throw new Error('Not a valid Jest backup');if(confirm('Importing will replace current saved data. Continue?')){db=x.data;save();location.reload()}}catch(e){alert(e.message)}};i.click()}
