function periodSymptomArt(key){return `<span class="period-symptom-art period-symptom-${key}" aria-hidden="true"></span>`}
function renderPeriod(){
 const n=daysIn(state.year,state.month),firstDay=new Date(state.year,state.month,1).getDay();
 let cal='<div class="period-calendar"><div class="period-weekday">Sun</div><div class="period-weekday">Mon</div><div class="period-weekday">Tue</div><div class="period-weekday">Wed</div><div class="period-weekday">Thu</div><div class="period-weekday">Fri</div><div class="period-weekday">Sat</div>';
 for(let i=0;i<firstDay;i++)cal+='<div class="period-cal-blank" aria-hidden="true"></div>';
 for(let d=1;d<=n;d++){
  const date=`${mk()}-${pad(d)}`,v=db.period[date]||{},ss=v.symptoms||[],bleed=(v.bleeding||'none').toLowerCase().replace(/\s+/g,'-');
  cal+=`<button class="period-cal-day period-bleed-${bleed}" onclick="openPeriod('${date}')" aria-label="${fmtDate(date)}"><span class="period-cal-date">${d}</span><span class="period-cal-symptoms">${ss.map(periodSymptomArt).join('')}</span></button>`;
 }
 cal+='</div>';
 const entries=Object.entries(db.period).filter(([k])=>k.startsWith(mk())),bleeding=entries.filter(([,v])=>v.bleeding).length;const counts={};entries.forEach(([,v])=>(v.symptoms||[]).forEach(x=>counts[x]=(counts[x]||0)+1));const common=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0];
 const bleedGuide=[['No bleeding','none'],['Spotting','spotting'],['Light','light'],['Moderate','moderate'],['Heavy','heavy']];
 main.innerHTML=`<section><div class="section-head"><div><h1 class="page-title">Period + Symptoms</h1><div class="subtle">Bleeding, symptoms and daily notes</div></div><button class="btn" onclick="openPeriod('${iso(today)}')">Log today</button></div>${monthNav()}<div class="card period-calendar-wrap">${cal}</div>
 <section class="section card"><div class="section-head"><h2>Bleeding colour guide</h2></div><div class="period-bleed-guide">${bleedGuide.map(x=>`<div class="period-bleed-key"><i class="period-bleed-swatch period-bleed-${x[1]}"></i><span>${x[0]}</span></div>`).join('')}</div></section>
 <section class="section card"><div class="section-head"><h2>Symptom legend</h2></div><div class="symptom-legend">${symptoms.map(s=>`<div class="symptom-chip"><img src="${symptomImg(s[1])}">${s[0]}</div>`).join('')}</div></section>
 <section class="section grid2">${card('Bleeding days',String(bleeding),'this month')}${card('Most common symptom',common?symptoms.find(s=>s[1]===common[0])?.[0]:'—',common?`${common[1]} day${common[1]===1?'':'s'}`:'none logged')}</section></section>`;
}

function renderWaterSugar(){const n=daysIn(state.year,state.month);let totalW=0,totalS=0,countW=0,countS=0;for(let d=1;d<=n;d++){const v=db.waterSugar[`${mk()}-${pad(d)}`]||{};if(v.water){totalW+=Number(v.water);countW++}if(v.sugar!=null){totalS+=Number(v.sugar);countS++}}
 main.innerHTML=`<section><div class="section-head"><div><h1 class="page-title">Water + Sugar</h1><div class="subtle">Monthly wheel dashboard</div></div><button class="btn" onclick="openWaterSugar('${iso(today)}')">Record today</button></div>${monthNav()}<div class="wheel-layout"><div class="card wheel-card" id="wheelCard"></div><div class="wheel-legend"><div class="card legend-block"><h3>Water · outer ring</h3>${[[1,'var(--blue1)'],[2,'var(--blue2)'],[3,'var(--blue3)']].map(x=>`<div class="legend-row"><i class="drop" style="background:${x[1]}"></i><span>${x[0]} L</span></div>`).join('')}</div><div class="card legend-block"><h3>Sugar · inner ring</h3>${[[0,'white'],[1,'var(--yellow1)'],[2,'var(--yellow2)'],[3,'var(--yellow3)']].map(x=>`<div class="legend-row"><i class="cube" style="background:${x[1]}"></i><span>${x[0]===0?'None':x[0]+' serving'+(x[0]>1?'s':'')}</span></div>`).join('')}</div></div></div>
 <div class="wheel-stats">${card('Total water',`${totalW} L`,countW?`${(totalW/countW).toFixed(1)} L average`:'no entries')}${card('Total sugar',`${totalS} servings`,countS?`${(totalS/countS).toFixed(1)} daily average`:'no entries')}</div><section class="section card"><div class="script" style="text-align:center">Fuel yourself well. You’ve got this! ♡</div></section></section>`; drawWheel();}
function polar(cx,cy,r,a){const rad=(a-90)*Math.PI/180;return {x:cx+r*Math.cos(rad),y:cy+r*Math.sin(rad)}}
function wedge(cx,cy,r1,r2,a0,a1){const p1=polar(cx,cy,r2,a0),p2=polar(cx,cy,r2,a1),p3=polar(cx,cy,r1,a1),p4=polar(cx,cy,r1,a0),large=a1-a0>180?1:0;return `M ${p1.x} ${p1.y} A ${r2} ${r2} 0 ${large} 1 ${p2.x} ${p2.y} L ${p3.x} ${p3.y} A ${r1} ${r1} 0 ${large} 0 ${p4.x} ${p4.y} Z`}
function drawWheel(){const el=$('#wheelCard');if(!el)return;const n=daysIn(state.year,state.month),step=360/n;let svg=`<svg viewBox="0 0 360 360"><circle cx="180" cy="180" r="72" fill="#f7fbfc"/>`;for(let d=1;d<=n;d++){const date=`${mk()}-${pad(d)}`,v=db.waterSugar[date]||{},wc={1:'#cfeaff',2:'#71b8ef',3:'#2474bd'}[v.water]||'#f4f8fa',sc={0:'#ffffff',1:'#fff4bd',2:'#ffd86b',3:'#f5aa22'}[v.sugar]||'#ffffff',a0=(d-1)*step+.7,a1=d*step-.7;svg+=`<path d="${wedge(180,180,118,164,a0,a1)}" fill="${wc}" stroke="#fff" onclick="openWaterSugar('${date}')"/><path d="${wedge(180,180,76,116,a0,a1)}" fill="${sc}" stroke="#fff" onclick="openWaterSugar('${date}')"/>`;const p=polar(180,180,96,(a0+a1)/2);svg+=`<text x="${p.x}" y="${p.y+3}" text-anchor="middle" class="wheel-day">${d}</text>`}svg+=`<text x="180" y="172" text-anchor="middle" class="wheel-center">${monthName(state.year,state.month)}</text><text x="180" y="192" text-anchor="middle" class="wheel-day">healthy habits · brighter days ♡</text></svg>`;el.innerHTML=svg}
