function renderSpending(){
 const ps=currentMonthPurchases(), inStore=ps.filter(p=>p.type==='inStore').reduce((s,p)=>s+Number(p.amount),0), online=ps.filter(p=>p.type==='online').reduce((s,p)=>s+Number(p.amount),0), total=inStore+online;
 const pct=Math.min(100,Math.round(total/(db.budgets.inStore+db.budgets.online)*100)||0);
 const cardSpent=c=>ps.filter(p=>p.card===c).reduce((s,p)=>s+Number(p.amount),0);
 const tax=ps.filter(p=>p.tax==='potential').reduce((s,p)=>s+Number(p.amount),0);
 const delivs=ps.filter(p=>p.type==='online'&&p.delivery&&new Date(p.delivery+'T12:00:00')>=new Date(new Date().toDateString())).sort((a,b)=>a.delivery.localeCompare(b.delivery)).slice(0,4);
 main.innerHTML=`<div class="shopping-page">
 <section class="card top-summary"><div class="section-head"><div><h1 class="page-title">Spending</h1><div class="subtle">Online + in-store shopping overview</div></div><button class="btn" onclick="openPurchase()">+ Add</button></div>${monthNav()}
 <div class="money">${fmtMoney(total)}</div><div class="subtle">of ${fmtMoney(db.budgets.inStore+db.budgets.online)} monthly budget</div><div class="mini-bar"><i style="width:${pct}%"></i></div></section>
 <section class="section spend-grid">${budgetTile('In store',inStore,db.budgets.inStore,'lav')}${budgetTile('Online',online,db.budgets.online,'sea')}</section>
 <section class="section card"><div class="section-head"><h2>Cards</h2><span class="subtle">money left</span></div><div class="grid2">${['Mx','Up','Co'].map(c=>{const left=db.cardLimits[c]-cardSpent(c);return `<div><strong>${c}</strong><div class="money" style="font-size:18px">${fmtMoney(left)}</div><div class="subtle">of ${fmtMoney(db.cardLimits[c])}</div></div>`}).join('')}</div></section>
 <section class="section card"><div class="week-total"><div><strong>This week</strong><div class="subtle">shopping total</div></div><div class="money">${fmtMoney(currentWeekTotal())}</div></div></section>
 <section class="section card"><div class="section-head"><h2>Shopping days</h2><span class="subtle">lavender = in store · sea-green = online</span></div>${shoppingCalendar(ps)}</section>
 <section class="section card"><div class="section-head"><h2>Recent purchases</h2><button class="btn secondary" onclick="openPurchase()">Add purchase</button></div><div class="purchase-list">${ps.length?ps.sort((a,b)=>b.date.localeCompare(a.date)).slice(0,8).map(purchaseRow).join(''):'<div class="empty">No purchases this month.</div>'}</div></section>
 <section class="section grid2">${card('Potential nurse deductions',fmtMoney(tax),'for review only','')}${card('Upcoming deliveries',String(delivs.length),delivs[0]?`next ${fmtDate(delivs[0].delivery)}`:'none recorded','')}</section>
 ${delivs.length?`<section class="section card"><div class="section-head"><h2>Upcoming deliveries</h2></div><div class="purchase-list">${delivs.map(p=>`<div class="purchase"><div><strong>${p.store} — ${p.item}</strong><small class="delivery">Expected ${fmtDate(p.delivery)}</small></div><div class="amt">${fmtMoney(p.amount)}</div></div>`).join('')}</div></section>`:''}
 <section class="section card notice">Potential tax-deductible tags are for organisation only, not a tax determination. Actual deductibility depends on ATO rules and your circumstances.</section>
 </div>`;
}
function budgetTile(label,spent,budget,kind){const remain=budget-spent,pct=Math.round(spent/budget*100)||0;const klass=remain<0?'over':pct>=85?'warn':'good';return `<div class="card budget-card ${kind==='sea'?'sea':''}"><h3>${label}</h3><div class="money">${fmtMoney(spent)}</div><div class="subtle">of ${fmtMoney(budget)}</div><div class="mini-bar"><i style="width:${Math.min(100,pct)}%;background:${kind==='sea'?'var(--sea-deep)':'var(--lav-deep)'}"></i></div><div class="pill ${klass}" style="margin-top:8px">${remain<0?`${fmtMoney(Math.abs(remain))} over`:`${fmtMoney(remain)} left`}</div></div>`}
function shoppingCalendar(ps){const n=daysIn(state.year,state.month);let h='<div class="calendar-mini">';for(let d=1;d<=n;d++){const date=`${mk()}-${pad(d)}`;const arr=ps.filter(p=>p.date===date);const cls=`${arr.some(p=>p.type==='inStore')?'shop-in':''} ${arr.some(p=>p.type==='online')?'shop-online':''}`;h+=`<div class="cal-day ${cls}">${d}</div>`}return h+'</div>'}
function purchaseRow(p){return `<div class="purchase"><div><strong>${p.store} — ${p.item}</strong><small>${fmtDate(p.date)} · ${p.type==='online'?'Online':'In store'} · ${p.card}${p.delivery?` · <span class="delivery">arrives ${fmtDate(p.delivery)}</span>`:''}</small><small class="${p.tax==='potential'?'tax-deductible':'tax-no'}">${p.tax==='potential'?'Potentially tax-deductible':'Not marked deductible'}</small></div><div class="amt">${fmtMoney(p.amount)}</div></div>`}
